name: Development workflow

on:
  push:
    branches:
      - develop

# Here the environment variable is declared in workflow level
env:
  # Replace with your Orchestrator Values 
  PROJECT_NAME: uipath.github.action                         
  PROJECT_FOLDER: ${{ github.action_path }}
  ORCH_URL: ${{ secrets.ORCH_URL }}
  ORCH_TENANT: ${{ secrets.ORCH_TENANT }}
  ORCH_CLIENT_ID: ${{ secrets.ORCH_CLIENT_ID }}
  ORCH_USER_KEY: ${{ secrets.ORCH_USER_KEY }}
  ORCH_ACC_NAME: ${{ secrets.ORCH_ACC_NAME }}

jobs:
  print-details:
    runs-on: ubuntu-latest
    steps:
      - name: echo-default-env-variables
        run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
  cleaner:
    runs-on: ubuntu-latest
    steps:
      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
   # Create Pull Request for Merge & Review
  create-pull-request:
    needs: cleaner
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "Pull Request From Github Action"
 